import { describe, expect, it } from "vitest";

import { getCatalogPriceGuidance, getCatalogPricePrefill, getCatalogPriceSignal } from "../lib/catalog";
import { annualAmount, buildRenewalCalendarExport, getArchivedSubscriptionInsights, getAttentionScore, getCategoryOverlapSuggestions, getCategorySpendTrend, getCurrencySpendGroups, getHouseholdAllocation, getHouseholdContributions, getLocalEvidenceIndex, getMonthlySpendTrend, getPlanChangeHistory, getPotentialDuplicateGroups, getRenewalReminderCopy, getReviewQueue, getSavingsImpact, getSpendSummary, getSubscriptionControlIssues, getSubscriptionOwnership, getTrialToPaidCountdowns, getUpcomingSubscriptions, isFutureDate, isTodayOrFutureDate, isValidDateString, monthlyAmount, nextLocalDateKey, resolveManagementUrl, sortDashboardSubscriptions, totalAnnual, totalMonthly } from "../lib/subscription-utils";
import { getCatalogInboxSummary } from "../lib/catalog-price-inbox";
import type { HouseholdMember, SubscriptionRecord } from "../lib/subscription-types";

const baseRecord: SubscriptionRecord = { id: "sub_1", serviceId: "chatgpt", planId: "plus", planName: "Plus", amount: 20, currency: "USD", cadence: "monthly", renewalDate: "2026-10-10", billingSource: "provider", status: "active", reminderEnabled: true, createdAt: "2026-08-13T00:00:00.000Z", updatedAt: "2026-08-13T00:00:00.000Z" };
const householdMembers: HouseholdMember[] = [{ id: "owner", name: "You", color: "#1A73E8", isOwner: true, createdAt: "2026-08-13T00:00:00.000Z" }, { id: "alex", name: "Alex", color: "#188038", createdAt: "2026-08-13T00:00:00.000Z" }];

describe("subscription calculations", () => {
  it("normalizes monthly, quarterly, and annual amounts", () => { expect(monthlyAmount(20, "monthly")).toBe(20); expect(monthlyAmount(30, "quarterly")).toBe(10); expect(monthlyAmount(120, "yearly")).toBe(10); expect(annualAmount(120, "yearly")).toBe(120); });
  it("excludes cancelled records from totals", () => { const cancelled = { ...baseRecord, id: "sub_2", amount: 100, cadence: "yearly" as const, status: "cancelled" as const }; expect(totalMonthly([baseRecord, cancelled])).toBe(20); expect(totalAnnual([baseRecord, cancelled])).toBe(240); });
  it("orders upcoming records by renewal date", () => { const later = { ...baseRecord, id: "sub_later", renewalDate: "2026-12-01" }; const earlier = { ...baseRecord, id: "sub_earlier", renewalDate: "2026-09-01" }; expect(getUpcomingSubscriptions([later, earlier]).map((item) => item.id)).toEqual(["sub_earlier", "sub_later"]); });
  it("sorts active dashboard records by next billing date or scheduled charge amount", () => { const later = { ...baseRecord, id: "sub_later", renewalDate: "2026-12-01", amount: 20 }; const earlier = { ...baseRecord, id: "sub_earlier", renewalDate: "2026-09-01", amount: 10 }; const annualHighCost = { ...baseRecord, id: "sub_annual", renewalDate: "2026-10-01", amount: 240, cadence: "yearly" as const }; expect(sortDashboardSubscriptions([later, earlier, annualHighCost], "upcoming").map((item) => item.id)).toEqual(["sub_earlier", "sub_annual", "sub_later"]); expect(sortDashboardSubscriptions([later, earlier, annualHighCost], "highest-cost").map((item) => item.id)).toEqual(["sub_annual", "sub_later", "sub_earlier"]); });
  it("summarizes monthly spend, category concentration, and near-term renewals", () => { const entertainment = { ...baseRecord, id: "sub_netflix", serviceId: "netflix", amount: 30, renewalDate: "2026-08-15" }; const summary = getSpendSummary([baseRecord, entertainment], new Date("2026-08-13T12:00:00")); expect(summary.monthly).toBe(50); expect(summary.categories[0]).toMatchObject({ category: "Entertainment", monthly: 30, percentage: 60 }); expect(summary.upcomingSevenDays.map((item) => item.id)).toEqual(["sub_netflix"]); expect(summary.insights.map((item) => item.id)).toContain("concentration"); expect(summary.insights.map((item) => item.id)).toContain("renewals"); });
  it("projects renewal charges into future monthly trend buckets", () => { const monthly = { ...baseRecord, renewalDate: "2026-08-15", amount: 12 }; const annual = { ...baseRecord, id: "sub_annual", renewalDate: "2026-09-01", amount: 120, cadence: "yearly" as const }; const trend = getMonthlySpendTrend([monthly, annual], new Date("2026-08-13T12:00:00"), 3); expect(trend).toEqual([{ label: "Aug", amount: 12 }, { label: "Sep", amount: 132 }, { label: "Oct", amount: 12 }]); });
  it("breaks the projected trend into service categories", () => { const ai = { ...baseRecord, renewalDate: "2026-08-15", amount: 20 }; const entertainment = { ...baseRecord, id: "sub_netflix", serviceId: "netflix", renewalDate: "2026-08-16", amount: 8 }; const categoryTrend = getCategorySpendTrend([ai, entertainment], new Date("2026-08-13T12:00:00"), 2); expect(categoryTrend.find((item) => item.category === "AI & work")?.points[0].amount).toBe(20); expect(categoryTrend.find((item) => item.category === "Entertainment")?.points[0].amount).toBe(8); });
  it("splits shared plans equally while keeping individual plans with the device owner", () => { const shared = { ...baseRecord, amount: 24, sharedMemberIds: ["owner", "alex"] }; const individual = { ...baseRecord, id: "sub_individual", amount: 10, sharedMemberIds: ["owner"] }; const contributions = getHouseholdContributions([shared, individual], householdMembers); expect(contributions.map((item) => ({ monthly: item.monthly, monthlyByCurrency: item.monthlyByCurrency.map((group) => ({ currency: group.currency, monthly: group.monthly })), sharedPlanCount: item.sharedPlanCount }))).toEqual([{ monthly: 22, monthlyByCurrency: [{ currency: "USD", monthly: 22 }], sharedPlanCount: 2 }, { monthly: 12, monthlyByCurrency: [{ currency: "USD", monthly: 12 }], sharedPlanCount: 1 }]); });
  it("keeps the device owner in the split and ignores unknown member IDs", () => { const shared = { ...baseRecord, amount: 30, sharedMemberIds: ["alex", "missing", "alex"] }; const contributions = getHouseholdContributions([shared], householdMembers); expect(contributions.map((item) => item.monthly)).toEqual([15, 15]); });
  it("does not count cancelled shared plans in household contributions", () => { const cancelled = { ...baseRecord, amount: 100, status: "cancelled" as const, sharedMemberIds: ["owner", "alex"] }; const contributions = getHouseholdContributions([cancelled], householdMembers); expect(contributions.map((item) => ({ monthly: item.monthly, groups: item.monthlyByCurrency, sharedPlanCount: item.sharedPlanCount }))).toEqual([{ monthly: 0, groups: [], sharedPlanCount: 0 }, { monthly: 0, groups: [], sharedPlanCount: 0 }]); });
  it("applies a saved custom allocation to household contributions", () => { const shared = { ...baseRecord, amount: 30, sharedMemberIds: ["owner", "alex"], sharedMemberShares: { owner: 70, alex: 30 } }; const contributions = getHouseholdContributions([shared], householdMembers); expect(contributions.map((item) => item.monthly)).toEqual([21, 9]); });
  it("falls back to an equal local allocation when custom percentages are invalid", () => { expect(getHouseholdAllocation(["owner", "alex"], { owner: 70, alex: 20 })).toEqual({ owner: 50, alex: 50 }); });
  it("builds an actionable review queue from trials, near renewals, and high costs", () => { const trial = { ...baseRecord, id: "sub_trial", status: "trial" as const, renewalDate: "2026-08-20" }; const queue = getReviewQueue([trial], new Date("2026-08-17T12:00:00")); expect(queue[0]?.reasons).toEqual(["trial", "renewal", "high-cost"]); });
  it("calculates selected cancellation savings without counting cancelled records", () => { const yearly = { ...baseRecord, id: "sub_yearly", amount: 120, cadence: "yearly" as const }; const cancelled = { ...baseRecord, id: "sub_cancelled", amount: 50, status: "cancelled" as const }; expect(getSavingsImpact([yearly, cancelled], ["sub_yearly", "sub_cancelled"])).toEqual({ monthly: 10, annual: 120 }); });
  it("separates mixed-currency summaries instead of combining their saved amounts", () => { const eur = { ...baseRecord, id: "sub_eur", amount: 15, currency: "EUR" }; const summary = getSpendSummary([baseRecord, eur]); expect(summary.hasMixedCurrencies).toBe(true); expect(summary.monthly).toBe(0); expect(summary.currencyGroups).toEqual([{ currency: "EUR", monthly: 15, annual: 180, subscriptionCount: 1 }, { currency: "USD", monthly: 20, annual: 240, subscriptionCount: 1 }]); expect(summary.categories).toEqual([]); expect(getCurrencySpendGroups([baseRecord, eur])).toHaveLength(2); });
  it("scores trial and near-renewal attention transparently", () => { const trial = { ...baseRecord, status: "trial" as const, amount: 60, renewalDate: "2026-08-20" }; expect(getAttentionScore(trial, new Date("2026-08-17T12:00:00"))).toBe(100); });
  it("flags local control risks for possible duplicates, short trials, annual renewals, unknown billing, and pending cancellation", () => {
    const duplicateA = { ...baseRecord, id: "dup_a", billingIdentity: "CARD • 1234", autoRenewStatus: "on" as const, renewalDate: "2026-08-30", cadence: "yearly" as const, amount: 120 };
    const duplicateB = { ...duplicateA, id: "dup_b", renewalDate: "2026-09-02" };
    const shortTrial = { ...baseRecord, id: "trial", serviceId: "netflix", planName: "Standard", status: "trial" as const, trialEndDate: "2026-08-19", renewalDate: "2026-08-19" };
    const pending = { ...baseRecord, id: "pending", serviceId: "claude", planName: "Pro", status: "uncertain" as const, billingSource: "unknown" as const, cancellationState: "pending" as const };
    const groups = getPotentialDuplicateGroups([duplicateA, duplicateB, shortTrial, pending]);
    const issues = getSubscriptionControlIssues([duplicateA, duplicateB, shortTrial, pending], new Date("2026-08-17T12:00:00"));
    expect(groups).toHaveLength(1);
    expect(groups[0]?.subscriptions.map((item) => item.id)).toEqual(["dup_a", "dup_b"]);
    expect(issues.map((item) => item.kind)).toEqual(expect.arrayContaining(["possible-duplicate", "category-overlap", "annual-renewal", "trial-deadline", "cancellation-follow-up", "billing-source", "billing-identity", "uncertain-status"]));
    expect(issues[0]?.kind).toBe("cancellation-follow-up");
  });
});

describe("subscription safety helpers", () => {
  it("accepts only real YYYY-MM-DD dates", () => { expect(isValidDateString("2026-09-15")).toBe(true); expect(isValidDateString("15-09-2026")).toBe(false); expect(isValidDateString("2026-02-31")).toBe(false); });
  it("requires a renewal date to be today or later", () => { const reference = new Date("2026-08-17T12:00:00"); expect(isTodayOrFutureDate("2026-08-16", reference)).toBe(false); expect(isTodayOrFutureDate("2026-08-17", reference)).toBe(true); expect(isTodayOrFutureDate("2026-08-18", reference)).toBe(true); expect(isTodayOrFutureDate("not-a-date", reference)).toBe(false); });
  it("requires the next renewal date to be strictly after today", () => { const reference = new Date("2026-08-17T12:00:00"); expect(nextLocalDateKey(reference)).toBe("2026-08-18"); expect(isFutureDate("2026-08-16", reference)).toBe(false); expect(isFutureDate("2026-08-17", reference)).toBe(false); expect(isFutureDate("2026-08-18", reference)).toBe(true); expect(isFutureDate("not-a-date", reference)).toBe(false); });
  it("routes store-billed subscriptions to the correct official management authority", () => { expect(resolveManagementUrl({ ...baseRecord, billingSource: "apple" })).toContain("apple.com"); expect(resolveManagementUrl({ ...baseRecord, billingSource: "google" })).toContain("play.google.com"); expect(resolveManagementUrl(baseRecord)).toContain("chatgpt.com"); });
  it("marks regional and variable catalog labels as non-fixed reference prices", () => { expect(getCatalogPriceSignal("Varies by country")).toBe("regional"); expect(getCatalogPriceSignal("From US$100/month")).toBe("variable"); expect(getCatalogPriceGuidance("Varies by country")).toContain("country"); });
  it("extracts a fixed catalog reference amount and preserves its explicit currency and cadence", () => { expect(getCatalogPricePrefill({ id: "plus", name: "Plus", priceLabel: "US$20/month", summary: "", features: [], cadence: "monthly" })).toEqual({ amount: 20, currency: "USD", cadence: "monthly" }); expect(getCatalogPricePrefill({ id: "annual", name: "Annual", priceLabel: "₹299/year", summary: "", features: [], cadence: "yearly" })).toEqual({ amount: 299, currency: "INR", cadence: "yearly" }); });
  it("does not prefill regional, variable, introductory, or free catalog labels", () => { expect(getCatalogPricePrefill({ id: "regional", name: "Regional", priceLabel: "Varies by country", summary: "", features: [], cadence: "monthly" })).toBeNull(); expect(getCatalogPricePrefill({ id: "seat", name: "Seats", priceLabel: "US$10/member/month", summary: "", features: [], cadence: "monthly" })).toBeNull(); expect(getCatalogPricePrefill({ id: "offer", name: "Offer", priceLabel: "₹139 for 2 months", summary: "", features: [], cadence: "monthly" })).toBeNull(); expect(getCatalogPricePrefill({ id: "free", name: "Free", priceLabel: "No subscription", summary: "", features: [], cadence: "monthly" })).toBeNull(); });
  it("builds local trial-to-paid and renewal-decision copy without claiming a provider charge", () => { const trial = { ...baseRecord, status: "trial" as const, trialEndDate: "2026-08-20", renewalDate: "2026-08-20", expectedNextCharge: 25 }; const countdowns = getTrialToPaidCountdowns([trial], new Date("2026-08-17T12:00:00")); expect(countdowns[0]).toMatchObject({ dueDate: "2026-08-20", dueInDays: 3, expectedCharge: 25 }); expect(getRenewalReminderCopy(trial)).toContain("may move"); const decided = { ...baseRecord, renewalDecisionPlan: { action: "downgrade" as const, decidedAt: "2026-08-01T00:00:00.000Z" } }; expect(getRenewalReminderCopy(decided)).toContain("downgrade"); });
  it("keeps ownership, category overlap, archive savings, and plan history separate by local record and currency", () => { const shared = { ...baseRecord, amount: 30, sharedMemberIds: ["owner", "alex"], sharedMemberShares: { owner: 60, alex: 40 }, planChangeHistory: [{ id: "latest", changedAt: "2026-08-15T00:00:00.000Z", previousPlanName: "Free", nextPlanName: "Plus", previousAmount: 0, nextAmount: 30, previousCurrency: "USD", nextCurrency: "USD", previousCadence: "monthly" as const, nextCadence: "monthly" as const }, { id: "earlier", changedAt: "2026-08-14T00:00:00.000Z", previousPlanName: "Trial", nextPlanName: "Free", previousAmount: 0, nextAmount: 0, previousCurrency: "USD", nextCurrency: "USD", previousCadence: "monthly" as const, nextCadence: "monthly" as const }] }; const claude = { ...baseRecord, id: "claude", serviceId: "claude", planName: "Pro" }; const cancelled = { ...baseRecord, id: "archived", status: "cancelled" as const, currency: "INR", amount: 1200, cadence: "yearly" as const }; expect(getSubscriptionOwnership(shared, householdMembers).map((item) => item.monthly)).toEqual([18, 12]); expect(getCategoryOverlapSuggestions([shared, claude])[0]?.category).toBe("AI & work"); expect(getArchivedSubscriptionInsights([shared, cancelled]).monthlySavingsByCurrency).toEqual([{ currency: "INR", monthly: 100, annual: 1200, subscriptionCount: 1 }]); expect(getPlanChangeHistory(shared).map((item) => item.id)).toEqual(["latest", "earlier"]); });
  it("indexes only user-entered evidence and creates detailed active-renewal calendar data", () => { const record = { ...baseRecord, billingIdentity: "OpenAI charge", costChangeReason: "Promotion ending", cancellationConfirmationReference: "CASE-1", notes: "Review before renewal", expectedNextCharge: 24, planChangeHistory: [{ id: "change", changedAt: "2026-08-15T00:00:00.000Z", previousPlanName: "Free", nextPlanName: "Plus", previousAmount: 0, nextAmount: 24, previousCurrency: "USD", nextCurrency: "USD", previousCadence: "monthly" as const, nextCadence: "monthly" as const }] }; const evidence = getLocalEvidenceIndex([record], [{ id: "charge_1", merchantLabel: "OpenAI", billingSource: "provider", paymentRail: "card", createdAt: "2026-08-12T00:00:00.000Z", updatedAt: "2026-08-12T00:00:00.000Z", matchedSubscriptionId: record.id }]); expect(evidence.map((item) => item.kind)).toEqual(expect.arrayContaining(["billing-clue", "price-context", "cancellation-reference", "plan-change", "charge-worksheet"])); const calendar = buildRenewalCalendarExport([record, { ...record, id: "cancelled", status: "cancelled" as const }], new Date("2026-08-16T00:00:00.000Z")); expect(calendar).toContain("Expected local charge:"); expect(calendar).toContain("Local note: Review before renewal"); expect(calendar).toContain("UID:subtrack-sub_1@local"); expect(calendar).not.toContain("subtrack-cancelled@local"); });
  it("summarizes the fixed India catalog-review baseline and local correction count", () => { expect(getCatalogInboxSummary([{ id: "draft", serviceName: "Spotify", country: "IN", createdAt: "2026-08-16T00:00:00.000Z" }])).toMatchObject({ reviewableSourceCount: 2, contextRequiredCount: 3, localCorrectionCount: 1 }); });
});
