import { describe, expect, it } from "vitest";

import { annualAmount, getAttentionScore, getCategorySpendTrend, getHouseholdAllocation, getHouseholdContributions, getMonthlySpendTrend, getReviewQueue, getSavingsImpact, getSpendSummary, getUpcomingSubscriptions, isFutureDate, isTodayOrFutureDate, isValidDateString, monthlyAmount, nextLocalDateKey, resolveManagementUrl, sortDashboardSubscriptions, totalAnnual, totalMonthly } from "../lib/subscription-utils";
import type { HouseholdMember, SubscriptionRecord } from "../lib/subscription-types";

const baseRecord: SubscriptionRecord = { id: "sub_1", serviceId: "chatgpt", planId: "plus", planName: "Plus", amount: 20, currency: "USD", cadence: "monthly", renewalDate: "2026-10-10", billingSource: "provider", status: "active", reminderEnabled: true, createdAt: "2026-08-13T00:00:00.000Z", updatedAt: "2026-08-13T00:00:00.000Z" };
const householdMembers: HouseholdMember[] = [{ id: "owner", name: "You", color: "#1A73E8", isOwner: true, createdAt: "2026-08-13T00:00:00.000Z" }, { id: "alex", name: "Alex", color: "#188038", createdAt: "2026-08-13T00:00:00.000Z" }];

describe("subscription calculations", () => {
  it("normalizes monthly, quarterly, and annual amounts", () => { expect(monthlyAmount(20, "monthly")).toBe(20); expect(monthlyAmount(30, "quarterly")).toBe(10); expect(monthlyAmount(120, "yearly")).toBe(10); expect(annualAmount(120, "yearly")).toBe(120); });
  it("excludes cancelled records from totals", () => { const cancelled = { ...baseRecord, id: "sub_2", amount: 100, cadence: "yearly" as const, status: "cancelled" as const }; expect(totalMonthly([baseRecord, cancelled])).toBe(20); expect(totalAnnual([baseRecord, cancelled])).toBe(240); });
  it("orders upcoming records by renewal date", () => { const later = { ...baseRecord, id: "sub_later", renewalDate: "2026-12-01" }; const earlier = { ...baseRecord, id: "sub_earlier", renewalDate: "2026-09-01" }; expect(getUpcomingSubscriptions([later, earlier]).map((item) => item.id)).toEqual(["sub_earlier", "sub_later"]); });
  it("sorts active dashboard records by next billing date or scheduled charge amount", () => { const later = { ...baseRecord, id: "sub_later", renewalDate: "2026-12-01", amount: 20 }; const earlier = { ...baseRecord, id: "sub_earlier", renewalDate: "2026-09-01", amount: 10 }; const annualHighCost = { ...baseRecord, id: "sub_annual", renewalDate: "2026-10-01", amount: 240, cadence: "yearly" as const }; expect(sortDashboardSubscriptions([later, earlier, annualHighCost], "upcoming").map((item) => item.id)).toEqual(["sub_earlier", "sub_annual", "sub_later"]); expect(sortDashboardSubscriptions([later, earlier, annualHighCost], "highest-cost").map((item) => item.id)).toEqual(["sub_annual", "sub_later", "sub_earlier"]); });
  it("summarizes monthly spend, category concentration, and near-term renewals", () => { const entertainment = { ...baseRecord, id: "sub_netflix", serviceId: "netflix", amount: 30, renewalDate: "2026-08-15" }; const summary = getSpendSummary([baseRecord, entertainment], new Date("2026-08-13T12:00:00")); expect(summary.monthly).toBe(50); expect(summary.categories[0]).toMatchObject({ category: "Entertainment", monthly: 30, percentage: 60 }); expect(summary.upcomingSevenDays.map((item) => item.id)).toEqual(["sub_netflix"]); expect(summary.insights.map((item) => item.id)).toContain("concentration"); expect(summary.insights.map((item) => item.id)).toContain("renewals"); });
  it("projects renewal charges into future monthly trend buckets", () => { const monthly = { ...baseRecord, renewalDate: "2026-08-15", amount: 12 }; const annual = { ...baseRecord, id: "sub_annual", renewalDate: "2026-09-01", amount: 120, cadence: "yearly" as const }; const trend = getMonthlySpendTrend([monthly, annual], new Date("2026-08-13T12:00:00"), 3); expect(trend).toEqual([{ label: "Aug", amount: 12 }, { label: "Sep", amount: 132 }, { label: "Oct", amount: 12 }]); });
  it("breaks the projected trend into service categories", () => { const ai = { ...baseRecord, renewalDate: "2026-08-15", amount: 20 }; const entertainment = { ...baseRecord, id: "sub_netflix", serviceId: "netflix", renewalDate: "2026-08-16", amount: 8 }; const categoryTrend = getCategorySpendTrend([ai, entertainment], new Date("2026-08-13T12:00:00"), 2); expect(categoryTrend.find((item) => item.category === "AI & work")?.points[0].amount).toBe(20); expect(categoryTrend.find((item) => item.category === "Entertainment")?.points[0].amount).toBe(8); });
  it("splits shared plans equally while keeping individual plans with the device owner", () => { const shared = { ...baseRecord, amount: 24, sharedMemberIds: ["owner", "alex"] }; const individual = { ...baseRecord, id: "sub_individual", amount: 10, sharedMemberIds: ["owner"] }; const contributions = getHouseholdContributions([shared, individual], householdMembers); expect(contributions).toEqual([{ member: householdMembers[0], monthly: 22, sharedPlanCount: 2 }, { member: householdMembers[1], monthly: 12, sharedPlanCount: 1 }]); });
  it("keeps the device owner in the split and ignores unknown member IDs", () => { const shared = { ...baseRecord, amount: 30, sharedMemberIds: ["alex", "missing", "alex"] }; const contributions = getHouseholdContributions([shared], householdMembers); expect(contributions).toEqual([{ member: householdMembers[0], monthly: 15, sharedPlanCount: 1 }, { member: householdMembers[1], monthly: 15, sharedPlanCount: 1 }]); });
  it("does not count cancelled shared plans in household contributions", () => { const cancelled = { ...baseRecord, amount: 100, status: "cancelled" as const, sharedMemberIds: ["owner", "alex"] }; const contributions = getHouseholdContributions([cancelled], householdMembers); expect(contributions).toEqual([{ member: householdMembers[0], monthly: 0, sharedPlanCount: 0 }, { member: householdMembers[1], monthly: 0, sharedPlanCount: 0 }]); });
  it("applies a saved custom allocation to household contributions", () => { const shared = { ...baseRecord, amount: 30, sharedMemberIds: ["owner", "alex"], sharedMemberShares: { owner: 70, alex: 30 } }; const contributions = getHouseholdContributions([shared], householdMembers); expect(contributions).toEqual([{ member: householdMembers[0], monthly: 21, sharedPlanCount: 1 }, { member: householdMembers[1], monthly: 9, sharedPlanCount: 1 }]); });
  it("falls back to an equal local allocation when custom percentages are invalid", () => { expect(getHouseholdAllocation(["owner", "alex"], { owner: 70, alex: 20 })).toEqual({ owner: 50, alex: 50 }); });
  it("builds an actionable review queue from trials, near renewals, and high costs", () => { const trial = { ...baseRecord, id: "sub_trial", status: "trial" as const, renewalDate: "2026-08-20" }; const queue = getReviewQueue([trial], new Date("2026-08-17T12:00:00")); expect(queue[0]?.reasons).toEqual(["trial", "renewal", "high-cost"]); });
  it("calculates selected cancellation savings without counting cancelled records", () => { const yearly = { ...baseRecord, id: "sub_yearly", amount: 120, cadence: "yearly" as const }; const cancelled = { ...baseRecord, id: "sub_cancelled", amount: 50, status: "cancelled" as const }; expect(getSavingsImpact([yearly, cancelled], ["sub_yearly", "sub_cancelled"])).toEqual({ monthly: 10, annual: 120 }); });
  it("scores trial and near-renewal attention transparently", () => { const trial = { ...baseRecord, status: "trial" as const, amount: 60, renewalDate: "2026-08-20" }; expect(getAttentionScore(trial, new Date("2026-08-17T12:00:00"))).toBe(100); });
});

describe("subscription safety helpers", () => {
  it("accepts only real YYYY-MM-DD dates", () => { expect(isValidDateString("2026-09-15")).toBe(true); expect(isValidDateString("15-09-2026")).toBe(false); expect(isValidDateString("2026-02-31")).toBe(false); });
  it("requires a renewal date to be today or later", () => { const reference = new Date("2026-08-17T12:00:00"); expect(isTodayOrFutureDate("2026-08-16", reference)).toBe(false); expect(isTodayOrFutureDate("2026-08-17", reference)).toBe(true); expect(isTodayOrFutureDate("2026-08-18", reference)).toBe(true); expect(isTodayOrFutureDate("not-a-date", reference)).toBe(false); });
  it("requires the next renewal date to be strictly after today", () => { const reference = new Date("2026-08-17T12:00:00"); expect(nextLocalDateKey(reference)).toBe("2026-08-18"); expect(isFutureDate("2026-08-16", reference)).toBe(false); expect(isFutureDate("2026-08-17", reference)).toBe(false); expect(isFutureDate("2026-08-18", reference)).toBe(true); expect(isFutureDate("not-a-date", reference)).toBe(false); });
  it("routes store-billed subscriptions to the correct official management authority", () => { expect(resolveManagementUrl({ ...baseRecord, billingSource: "apple" })).toContain("apple.com"); expect(resolveManagementUrl({ ...baseRecord, billingSource: "google" })).toContain("play.google.com"); expect(resolveManagementUrl(baseRecord)).toContain("chatgpt.com"); });
});
