import { router } from "expo-router";
import { useThemedStyles } from "@/lib/ui-theme";
import { useMoneyFormatter } from "@/lib/privacy";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useSubscriptions } from "@/lib/subscription-store";
import { formatDate, getArchivedSubscriptionInsights } from "@/lib/subscription-utils";
import { getService } from "@/lib/catalog";

const type = { regular: "Poppins-Regular", semi: "Poppins-SemiBold", bold: "Poppins-Bold" };

const baseStyles = () => styles;
export default function ArchiveInsightsScreen() {
  const styles = useThemedStyles(baseStyles());
  const formatCurrency = useMoneyFormatter();
  const { subscriptions } = useSubscriptions();
  const archived = subscriptions.filter((item) => item.status === "cancelled").sort((left, right) => right.updatedAt.localeCompare(left.updatedAt));
  const insight = getArchivedSubscriptionInsights(subscriptions);
  return <ScreenContainer className="px-5" containerClassName="bg-background" edges={["top", "bottom", "left", "right"]}><FlatList data={archived} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View><View style={styles.nav}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} hitSlop={10}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.navTitle}>Archive insights</Text><View style={styles.spacer} /></View><Text style={styles.title}>What you marked stopped</Text><Text style={styles.subtitle}>These are local cancellation records, not provider-confirmed billing outcomes. Savings remain separated by currency.</Text><View style={styles.summary}><Text style={styles.summaryNumber}>{insight.archivedCount}</Text><Text style={styles.summaryLabel}>subscriptions archived locally</Text>{insight.monthlySavingsByCurrency.map((group) => <Text key={group.currency} style={styles.saving}>{formatCurrency(group.monthly, group.currency)}/month estimated · {formatCurrency(group.annual, group.currency)}/year</Text>)}</View><Text style={styles.section}>Archived records</Text></View>} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => router.push(`/subscription/${item.id}` as never)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View><Text style={styles.itemTitle}>{getService(item.serviceId)?.name ?? item.planName}</Text><Text style={styles.detail}>{item.planName} · {formatCurrency(item.amount, item.currency)} · {item.cadence}</Text><Text style={styles.date}>Updated {formatDate(item.updatedAt)}</Text></View><Text style={styles.chevron}>›</Text></Pressable>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No archived subscriptions</Text><Text style={styles.emptyBody}>When you mark a provider-confirmed cancellation locally, it will appear here with a separate-by-currency savings estimate.</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 10, flexGrow: 1, paddingBottom: 30, paddingTop: 10 }, nav: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, back: { color: "#F4F2E8", fontFamily: type.regular, fontSize: 34, lineHeight: 34 }, navTitle: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 13 }, spacer: { width: 24 }, title: { color: "#F4F2E8", fontFamily: type.bold, fontSize: 25, letterSpacing: -0.7, marginTop: 8 }, subtitle: { color: "#A8AD98", fontFamily: type.regular, fontSize: 11, lineHeight: 17, marginTop: 4 }, summary: { backgroundColor: "#202713", borderColor: "#485632", borderRadius: 13, borderWidth: 1, marginTop: 12, padding: 14 }, summaryNumber: { color: "#C9F72D", fontFamily: type.bold, fontSize: 27 }, summaryLabel: { color: "#C5CBB8", fontFamily: type.regular, fontSize: 10, marginTop: 2 }, saving: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 11, marginTop: 9 }, section: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 15, marginTop: 5 }, card: { alignItems: "center", backgroundColor: "#191E0F", borderColor: "#343A25", borderRadius: 13, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 72, padding: 13 }, itemTitle: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 13 }, detail: { color: "#C5CBB8", fontFamily: type.regular, fontSize: 10, marginTop: 3 }, date: { color: "#89917A", fontFamily: type.regular, fontSize: 9, marginTop: 5 }, chevron: { color: "#C9F72D", fontFamily: type.regular, fontSize: 25 }, empty: { alignItems: "center", backgroundColor: "#202713", borderColor: "#485632", borderRadius: 13, borderWidth: 1, marginTop: 4, padding: 24 }, emptyTitle: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 13 }, emptyBody: { color: "#A8AD98", fontFamily: type.regular, fontSize: 10, lineHeight: 15, marginTop: 5, textAlign: "center" }, pressed: { opacity: 0.75 } });
