import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useSubscriptions } from "@/lib/subscription-store";

const type = { regular: "Poppins-Regular", semi: "Poppins-SemiBold", bold: "Poppins-Bold" };

export default function CatalogCorrectionScreen() {
  const { saveCatalogCorrectionRequest } = useSubscriptions();
  const [serviceName, setServiceName] = useState(""); const [country, setCountry] = useState("IN"); const [planName, setPlanName] = useState(""); const [observedPrice, setObservedPrice] = useState(""); const [sourceUrl, setSourceUrl] = useState(""); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false);
  const save = async () => {
    if (!serviceName.trim() || !country.trim()) return Alert.alert("Add the service and country", "Include a service name and a two-letter country code so the local draft has useful context.");
    if (sourceUrl.trim() && !/^https:\/\//i.test(sourceUrl.trim())) return Alert.alert("Use an official HTTPS link", "Add the provider’s official page beginning with https://, or leave the link blank.");
    try { setSaving(true); await saveCatalogCorrectionRequest({ serviceName, country, planName, observedPrice, sourceUrl, note }); Alert.alert("Correction saved locally", "This stays on your device for review. It does not update the catalog or send data automatically.", [{ text: "Done", onPress: () => router.back() }]); } finally { setSaving(false); }
  };
  return <ScreenContainer className="px-5" containerClassName="bg-background" edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="always"><View style={styles.nav}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} hitSlop={10}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.navTitle}>Catalog correction</Text><View style={styles.spacer} /></View><Text style={styles.title}>Record an official source</Text><Text style={styles.subtitle}>Save an on-device draft for a plan, price, link, or availability correction. It does not publish a change or contact the provider.</Text><Field label="Service name *" value={serviceName} onChangeText={setServiceName} placeholder="e.g. Spotify" /><Field label="Country code *" value={country} onChangeText={setCountry} placeholder="IN" autoCapitalize="characters" maxLength={2} /><Field label="Plan name" value={planName} onChangeText={setPlanName} placeholder="e.g. Individual" /><Field label="Observed price wording" value={observedPrice} onChangeText={setObservedPrice} placeholder="e.g. ₹139/month after trial" /><Field label="Official source link" value={sourceUrl} onChangeText={setSourceUrl} placeholder="https://provider.example/pricing" autoCapitalize="none" keyboardType="url" /><Field label="Note" value={note} onChangeText={setNote} placeholder="Eligibility, tax, billing channel, or reason to review" multiline /><View style={styles.boundary}><Text style={styles.boundaryTitle}>Review boundary</Text><Text style={styles.boundaryBody}>Only provider-owned pages can support a catalog reference. Promotional, student, tax, store, carrier, and account conditions must remain visible. Your saved subscription amounts are not changed.</Text></View><Pressable disabled={saving} accessibilityRole="button" onPress={() => void save()} style={({ pressed }) => [styles.primary, (pressed || saving) && styles.pressed]}><Text style={styles.primaryText}>{saving ? "Saving…" : "Save local correction"}</Text></Pressable></ScrollView></ScreenContainer>;
}

function Field({ label, multiline, ...props }: { label: string; multiline?: boolean; value: string; onChangeText: (value: string) => void; placeholder: string; autoCapitalize?: "none" | "characters"; maxLength?: number; keyboardType?: "url" }) { return <View><Text style={styles.label}>{label}</Text><TextInput {...props} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} placeholderTextColor="#727A62" style={[styles.input, multiline && styles.noteInput]} /></View>; }

const styles = StyleSheet.create({ content: { gap: 11, paddingBottom: 30, paddingTop: 10 }, nav: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, back: { color: "#F4F2E8", fontFamily: type.regular, fontSize: 34, lineHeight: 34 }, navTitle: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 13 }, spacer: { width: 24 }, title: { color: "#F4F2E8", fontFamily: type.bold, fontSize: 25, letterSpacing: -0.7, marginTop: 8 }, subtitle: { color: "#A8AD98", fontFamily: type.regular, fontSize: 11, lineHeight: 17, marginBottom: 4, marginTop: 4 }, label: { color: "#A8AD98", fontFamily: type.semi, fontSize: 10, marginBottom: 5 }, input: { backgroundColor: "#191E0F", borderColor: "#3A4227", borderRadius: 12, borderWidth: 1, color: "#F4F2E8", fontFamily: type.regular, fontSize: 12, height: 46, paddingHorizontal: 12 }, noteInput: { minHeight: 88, paddingTop: 12 }, boundary: { backgroundColor: "#202713", borderColor: "#485632", borderRadius: 12, borderWidth: 1, padding: 12 }, boundaryTitle: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 12 }, boundaryBody: { color: "#C5CBB8", fontFamily: type.regular, fontSize: 10, lineHeight: 15, marginTop: 4 }, primary: { alignItems: "center", backgroundColor: "#C9F72D", borderRadius: 12, justifyContent: "center", minHeight: 48, marginTop: 3 }, primaryText: { color: "#172108", fontFamily: type.semi, fontSize: 12 }, pressed: { opacity: 0.75 } });
