import { router } from "expo-router";
import { useThemedStyles } from "@/lib/ui-theme";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useSubscriptions } from "@/lib/subscription-store";
import { formatDate, getLocalEvidenceIndex } from "@/lib/subscription-utils";

const type = { regular: "Poppins-Regular", semi: "Poppins-SemiBold", bold: "Poppins-Bold" };

const baseStyles = () => styles;
export default function EvidenceIndexScreen() {
  const styles = useThemedStyles(baseStyles());
  const { subscriptions, chargeRecognitionCases } = useSubscriptions();
  const evidence = getLocalEvidenceIndex(subscriptions, chargeRecognitionCases);
  return <ScreenContainer className="px-5" containerClassName="bg-background" edges={["top", "bottom", "left", "right"]}><FlatList data={evidence} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View><View style={styles.nav}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} hitSlop={10}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.navTitle}>Evidence index</Text><View style={styles.spacer} /></View><Text style={styles.title}>Your local references</Text><Text style={styles.subtitle}>A private index of billing labels, plan-change notes, cancellation references, and charge worksheets you entered yourself. No receipt, inbox, or account is scanned.</Text><View style={styles.count}><Text style={styles.countNumber}>{evidence.length}</Text><Text style={styles.countLabel}>saved local references</Text></View></View>} renderItem={({ item }) => <Pressable disabled={!item.subscriptionId} accessibilityRole={item.subscriptionId ? "button" : undefined} onPress={() => item.subscriptionId && router.push(`/subscription/${item.subscriptionId}` as never)} style={({ pressed }) => [styles.card, pressed && item.subscriptionId && styles.pressed]}><View style={styles.cardTop}><Text style={styles.kind}>{item.kind.replace(/-/g, " ")}</Text><Text style={styles.date}>{formatDate(item.date)}</Text></View><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.detail}>{item.detail}</Text>{item.subscriptionId ? <Text style={styles.open}>Open subscription ›</Text> : null}</Pressable>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No local references yet</Text><Text style={styles.emptyBody}>Add a billing clue, cancellation reference, price context, plan change, or charge-recognition worksheet to build your own private index.</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 10, flexGrow: 1, paddingBottom: 30, paddingTop: 10 }, nav: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, back: { color: "#F4F2E8", fontFamily: type.regular, fontSize: 34, lineHeight: 34 }, navTitle: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 13 }, spacer: { width: 24 }, title: { color: "#F4F2E8", fontFamily: type.bold, fontSize: 25, letterSpacing: -0.7, marginTop: 8 }, subtitle: { color: "#A8AD98", fontFamily: type.regular, fontSize: 11, lineHeight: 17, marginTop: 4 }, count: { alignItems: "baseline", backgroundColor: "#202713", borderColor: "#485632", borderRadius: 12, borderWidth: 1, flexDirection: "row", gap: 7, marginTop: 12, padding: 13 }, countNumber: { color: "#C9F72D", fontFamily: type.bold, fontSize: 22 }, countLabel: { color: "#C5CBB8", fontFamily: type.regular, fontSize: 10 }, card: { backgroundColor: "#191E0F", borderColor: "#343A25", borderRadius: 13, borderWidth: 1, padding: 13 }, cardTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, kind: { color: "#C9F72D", fontFamily: type.semi, fontSize: 9, textTransform: "capitalize" }, date: { color: "#89917A", fontFamily: type.regular, fontSize: 9 }, itemTitle: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 12, marginTop: 5 }, detail: { color: "#A8AD98", fontFamily: type.regular, fontSize: 10, lineHeight: 15, marginTop: 4 }, open: { color: "#C9F72D", fontFamily: type.semi, fontSize: 10, marginTop: 9 }, empty: { alignItems: "center", backgroundColor: "#202713", borderColor: "#485632", borderRadius: 13, borderWidth: 1, marginTop: 4, padding: 24 }, emptyTitle: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 13 }, emptyBody: { color: "#A8AD98", fontFamily: type.regular, fontSize: 10, lineHeight: 15, marginTop: 5, textAlign: "center" }, pressed: { opacity: 0.75 } });
