import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";

const type = { regular: "Poppins-Regular", semi: "Poppins-SemiBold", bold: "Poppins-Bold" };

const sections = [
  ["What SubTrack does", "SubTrack helps people organize subscription records, renewal dates, expected charges, household allocations, local notes, and official-management links. It does not access bank accounts, payment cards, email inboxes, provider passwords, or provider billing controls."],
  ["Data stored on your device", "Subscription records, renewal plans, value checks, evidence references, catalog-correction drafts, household information, and reminder preferences are stored locally on the device by default. Local notification scheduling stays on the device."],
  ["Optional cloud sync", "If you choose to create a cloud account, your email address, display name, and the SubTrack backup snapshot you explicitly sync are processed by Supabase to provide account sign-in and cross-device backup. Cloud sync is optional and manual. We do not sell personal data."],
  ["Sharing and disclosures", "SubTrack does not sell personal data or share it for advertising. When you use your device’s share sheet to export local data or a renewal calendar, you choose the recipient and service that receives that export."],
  ["Retention and deletion", "Local data remains until you delete it from SubTrack or uninstall the app, subject to your device’s backup settings. You can delete an optional cloud account and its remote backup from Profile or the public Account deletion page. Local records are not automatically removed when the cloud account is deleted."],
  ["Permissions", "SubTrack requests notification permission only after you choose to enable renewal reminders. Denying permission does not prevent core subscription tracking. The production release removes unrelated microphone access."],
  ["Contact and final publication", "This in-app policy describes the current application behavior. Before public Play Store submission, the publisher must add its legal name and a monitored privacy contact to the hosted policy and matching Play Store listing."],
];

export default function PrivacyPolicyScreen() {
  return <ScreenContainer className="px-5" containerClassName="bg-background" edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.nav}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} hitSlop={10}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.navTitle}>Privacy policy</Text><View style={styles.spacer} /></View><Text style={styles.eyebrow}>SUBTRACK / PRIVACY</Text><Text style={styles.title}>Privacy policy</Text><Text style={styles.updated}>Last updated: 27 August 2026</Text><Text style={styles.intro}>This policy explains how SubTrack handles information. It is designed for a privacy-first, local-first subscription organizer.</Text>{sections.map(([heading, body]) => <View key={heading} style={styles.section}><Text style={styles.heading}>{heading}</Text><Text style={styles.body}>{body}</Text></View>)}<View style={styles.deleteCard}><Text style={styles.deleteTitle}>Need to delete an optional cloud account?</Text><Text style={styles.deleteBody}>Sign in to the account you want to remove, then confirm account deletion. The action removes the remote account and backup; it does not cancel third-party subscriptions.</Text><Pressable accessibilityRole="button" onPress={() => router.push("/delete-account" as never)} style={({ pressed }) => [styles.deleteButton, pressed && styles.pressed]}><Text style={styles.deleteButtonText}>Open account deletion</Text></Pressable></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingBottom: 32, paddingTop: 10 }, nav: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, back: { color: "#F4F2E8", fontFamily: type.regular, fontSize: 34, lineHeight: 34 }, navTitle: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 13 }, spacer: { width: 24 }, eyebrow: { color: "#C9F72D", fontFamily: type.semi, fontSize: 9, letterSpacing: 1, marginTop: 16 }, title: { color: "#F4F2E8", fontFamily: type.bold, fontSize: 28, letterSpacing: -0.8, marginTop: 6 }, updated: { color: "#89917A", fontFamily: type.regular, fontSize: 10, marginTop: 5 }, intro: { color: "#C5CBB8", fontFamily: type.regular, fontSize: 12, lineHeight: 18, marginTop: 19 }, section: { borderTopColor: "#343A25", borderTopWidth: 1, marginTop: 18, paddingTop: 16 }, heading: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 14 }, body: { color: "#A8AD98", fontFamily: type.regular, fontSize: 11, lineHeight: 17, marginTop: 5 }, deleteCard: { backgroundColor: "#202713", borderColor: "#485632", borderRadius: 14, borderWidth: 1, marginTop: 22, padding: 15 }, deleteTitle: { color: "#F4F2E8", fontFamily: type.semi, fontSize: 13 }, deleteBody: { color: "#C5CBB8", fontFamily: type.regular, fontSize: 10, lineHeight: 15, marginTop: 5 }, deleteButton: { alignItems: "center", borderColor: "#C9F72D", borderRadius: 10, borderWidth: 1, justifyContent: "center", marginTop: 12, minHeight: 42 }, deleteButtonText: { color: "#C9F72D", fontFamily: type.semi, fontSize: 11 }, pressed: { opacity: 0.72 } });
