import { Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { useEffect, useMemo, useState } from "react";

const weekdays = ["S", "M", "T", "W", "T", "F", "S"];
const type = { regular: "Poppins-Regular", semi: "Poppins-SemiBold", bold: "Poppins-Bold" };

function toKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function parseKey(value?: string) { const date = value ? new Date(`${value}T00:00:00`) : new Date(); return Number.isNaN(date.getTime()) ? new Date() : date; }

export function DatePickerSheet({ visible, value, title, onClose, onSelect }: { visible: boolean; value?: string; title: string; onClose: () => void; onSelect: (date: string) => void }) {
  const [displayedMonth, setDisplayedMonth] = useState(() => new Date(parseKey(value).getFullYear(), parseKey(value).getMonth(), 1));
  useEffect(() => { if (visible) { const date = parseKey(value); setDisplayedMonth(new Date(date.getFullYear(), date.getMonth(), 1)); } }, [value, visible]);
  const days = useMemo(() => { const start = new Date(displayedMonth.getFullYear(), displayedMonth.getMonth(), 1); const first = new Date(displayedMonth.getFullYear(), displayedMonth.getMonth(), 1 - start.getDay()); return Array.from({ length: 42 }, (_, index) => { const date = new Date(first.getFullYear(), first.getMonth(), first.getDate() + index); return { date, key: toKey(date), current: date.getMonth() === displayedMonth.getMonth() }; }); }, [displayedMonth]);
  const selected = value ?? "";
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.header}><Text style={styles.title}>{title}</Text><Pressable onPress={onClose} hitSlop={10}><Text style={styles.close}>×</Text></Pressable></View><View style={styles.monthNav}><Pressable onPress={() => setDisplayedMonth(new Date(displayedMonth.getFullYear(), displayedMonth.getMonth() - 1, 1))} style={styles.navButton}><Text style={styles.navText}>‹</Text></Pressable><Text style={styles.month}>{new Intl.DateTimeFormat(undefined, { month: "long", year: "numeric" }).format(displayedMonth)}</Text><Pressable onPress={() => setDisplayedMonth(new Date(displayedMonth.getFullYear(), displayedMonth.getMonth() + 1, 1))} style={styles.navButton}><Text style={styles.navText}>›</Text></Pressable></View><View style={styles.weekdays}>{weekdays.map((day, index) => <Text key={`${day}-${index}`} style={styles.weekday}>{day}</Text>)}</View><View style={styles.grid}>{days.map((item) => { const isSelected = item.key === selected; const today = item.key === toKey(new Date()); return <Pressable key={item.key} onPress={() => { onSelect(item.key); onClose(); }} style={({ pressed }) => [styles.day, isSelected && styles.daySelected, today && !isSelected && styles.dayToday, pressed && styles.pressed]}><Text style={[styles.dayText, !item.current && styles.dayMuted, isSelected && styles.daySelectedText, today && !isSelected && styles.dayTodayText]}>{item.date.getDate()}</Text></Pressable>; })}</View><Pressable onPress={() => { onSelect(toKey(new Date())); onClose(); }} style={styles.todayButton}><Text style={styles.todayText}>Use today</Text></Pressable></View></View></Modal>;
}

const styles = StyleSheet.create({ backdrop: { backgroundColor: "rgba(32,33,36,0.45)", flex: 1, justifyContent: "flex-end" }, sheet: { backgroundColor: "#FFFFFF", borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20 }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, title: { color: "#202124", fontFamily: type.semi, fontSize: 16 }, close: { color: "#5F6368", fontFamily: type.regular, fontSize: 28, lineHeight: 28 }, monthNav: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 15 }, navButton: { alignItems: "center", backgroundColor: "#F1F3F4", borderRadius: 18, height: 36, justifyContent: "center", width: 36 }, navText: { color: "#1A73E8", fontFamily: type.regular, fontSize: 25, lineHeight: 25 }, month: { color: "#202124", fontFamily: type.semi, fontSize: 14 }, weekdays: { flexDirection: "row", marginTop: 16 }, weekday: { color: "#5F6368", fontFamily: type.semi, fontSize: 10, textAlign: "center", width: "14.2857%" }, grid: { flexDirection: "row", flexWrap: "wrap", marginTop: 7 }, day: { alignItems: "center", borderRadius: 18, height: 38, justifyContent: "center", width: "14.2857%" }, dayText: { color: "#202124", fontFamily: type.regular, fontSize: 12 }, dayMuted: { color: "#BDC1C6" }, dayToday: { borderColor: "#1A73E8", borderWidth: 1 }, dayTodayText: { color: "#1967D2", fontFamily: type.semi }, daySelected: { backgroundColor: "#1A73E8" }, daySelectedText: { color: "#FFFFFF", fontFamily: type.semi }, todayButton: { alignItems: "center", marginTop: 12, paddingVertical: 10 }, todayText: { color: "#1A73E8", fontFamily: type.semi, fontSize: 13 }, pressed: { opacity: 0.72 } });
