import type { BillingSource, CatalogPlan, ServiceDefinition } from "./subscription-types";

const plans = (items: Array<Omit<CatalogPlan, "cadence"> & { cadence?: CatalogPlan["cadence"] }>) =>
  items.map((item) => ({ cadence: "monthly" as const, ...item }));

export const serviceLogoSources: Record<string, string> = {
  chatgpt: "https://commons.wikimedia.org/wiki/Special:FilePath/ChatGPT_logo.svg",
  claude: "https://cdn.simpleicons.org/anthropic",
  netflix: "https://cdn.simpleicons.org/netflix",
  "prime-video": "https://www.google.com/s2/favicons?domain=amazon.com&sz=128",
  spotify: "https://cdn.simpleicons.org/spotify",
  "youtube-premium": "https://cdn.simpleicons.org/youtube",
  "microsoft-365": "https://www.google.com/s2/favicons?domain=microsoft.com&sz=128",
  "google-one": "https://cdn.simpleicons.org/google",
  notion: "https://cdn.simpleicons.org/notion",
  "apple-music": "https://cdn.simpleicons.org/applemusic",
  headspace: "https://cdn.simpleicons.org/headspace",
  coursera: "https://cdn.simpleicons.org/coursera",
  "playstation-plus": "https://cdn.simpleicons.org/playstation",
  perplexity: "https://cdn.simpleicons.org/perplexity",
  grammarly: "https://cdn.simpleicons.org/grammarly",
  dropbox: "https://cdn.simpleicons.org/dropbox",
  canva: "https://cdn.simpleicons.org/canva",
  "disney-plus": "https://cdn.simpleicons.org/disneyplus",
  hulu: "https://cdn.simpleicons.org/hulu",
  audible: "https://cdn.simpleicons.org/audible",
  strava: "https://cdn.simpleicons.org/strava",
  "xbox-game-pass": "https://cdn.simpleicons.org/xbox",
  duolingo: "https://cdn.simpleicons.org/duolingo",
};

export const services: ServiceDefinition[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: "AI & work",
    initials: "C",
    accent: "#0F766E",
    description: "A conversational AI workspace for writing, analysis, research, and everyday tasks.",
    officialUrl: "https://chatgpt.com/",
    managementUrl: "https://chatgpt.com/",
    managementHint: "Sign in, then open Settings to review your plan and billing options.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Core everyday AI access.", features: ["General chat", "Basic access", "Personal use"] },
      { id: "plus", name: "Plus", priceLabel: "US$20/month", summary: "Expanded access for frequent individual use.", features: ["Higher limits", "Priority access", "More tools"] },
      { id: "pro", name: "Pro", priceLabel: "US$200/month", summary: "Higher-capacity access for power users.", features: ["Highest limits", "Advanced tools", "Priority access"] },
    ]),
  },
  {
    id: "claude",
    name: "Claude",
    category: "AI & work",
    initials: "Cl",
    accent: "#C76B42",
    description: "An AI assistant for writing, reasoning, document work, and creative tasks.",
    officialUrl: "https://claude.ai/",
    managementUrl: "https://claude.ai/",
    managementHint: "Sign in, then open account settings to view plan and billing controls.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Try core AI capabilities.", features: ["Core chat", "Limited use", "Personal workspace"] },
      { id: "pro", name: "Pro", priceLabel: "US$20/month", summary: "More capacity for regular work.", features: ["Higher usage", "Priority access", "More features"] },
      { id: "max", name: "Max", priceLabel: "From US$100/month", summary: "Expanded access for intensive usage.", features: ["High capacity", "Priority access", "Advanced usage"] },
    ]),
  },
  {
    id: "netflix",
    name: "Netflix",
    category: "Entertainment",
    initials: "N",
    accent: "#B91C1C",
    description: "A streaming entertainment service with plans that vary by country and feature set.",
    officialUrl: "https://www.netflix.com/",
    managementUrl: "https://www.netflix.com/cancelplan",
    managementHint: "Sign in to review membership or cancellation options for direct Netflix billing.",
    plans: plans([
      { id: "standard-ads", name: "Standard with ads", priceLabel: "Varies by country", summary: "Streaming access with advertising in eligible regions.", features: ["Ad-supported", "Selected devices", "Regional availability"] },
      { id: "standard", name: "Standard", priceLabel: "Varies by country", summary: "Ad-free streaming for most households.", features: ["Ad-free viewing", "Multiple devices", "HD where available"] },
      { id: "premium", name: "Premium", priceLabel: "Varies by country", summary: "Highest available quality and device allowance.", features: ["More devices", "Higher quality", "Ad-free viewing"] },
    ]),
  },
  {
    id: "prime-video",
    name: "Amazon Prime",
    category: "Entertainment",
    initials: "A",
    accent: "#1D4ED8",
    description: "A membership that can include delivery, entertainment, and regional benefits.",
    officialUrl: "https://www.amazon.com/prime",
    managementUrl: "https://www.amazon.com/gp/primecentral",
    managementHint: "Sign in to Amazon and open Prime Membership to review your direct membership.",
    plans: plans([
      { id: "monthly", name: "Monthly", priceLabel: "US$14.99/month", summary: "Flexible membership cadence.", features: ["Monthly billing", "Prime benefits", "Regional terms"] },
      { id: "annual", name: "Annual", cadence: "yearly", priceLabel: "US$139/year", summary: "Annual membership cadence.", features: ["Annual billing", "Prime benefits", "Regional terms"] },
      { id: "video", name: "Prime Video", priceLabel: "See official price", summary: "Video access may be offered separately in some regions.", features: ["Video access", "Regional catalog", "Optional channels"] },
    ]),
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "Music",
    initials: "S",
    accent: "#15803D",
    description: "Music and audio streaming with individual, shared, and student options in supported regions.",
    officialUrl: "https://www.spotify.com/",
    managementUrl: "https://www.spotify.com/account/subscription/",
    managementHint: "Sign in to review your plan. If billed by a partner, Spotify will identify that provider.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Ad-supported listening.", features: ["Ad-supported", "Core music access", "Mobile limits"] },
      { id: "premium", name: "Premium Individual", priceLabel: "US$12.99/month", summary: "Ad-free listening for one account.", features: ["Ad-free", "Offline listening", "Individual account"] },
      { id: "family", name: "Premium Family", priceLabel: "US$21.99/month", summary: "A household plan where available.", features: ["Multiple accounts", "Household plan", "Parental features"] },
    ]),
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    category: "Entertainment",
    initials: "Y",
    accent: "#DC2626",
    description: "An ad-free YouTube membership with region-dependent plan and family options.",
    officialUrl: "https://www.youtube.com/premium",
    managementUrl: "https://www.youtube.com/paid_memberships",
    managementHint: "Open paid memberships while signed in to review eligible plan controls.",
    plans: plans([
      { id: "individual", name: "Individual", priceLabel: "US$15.99/month", summary: "Ad-free viewing for one person.", features: ["Ad-free viewing", "Background play", "Downloads"] },
      { id: "family", name: "Family", priceLabel: "US$26.99/month", summary: "Shared household access where available.", features: ["Multiple members", "Household rules", "Regional availability"] },
      { id: "student", name: "Student", priceLabel: "US$8.99/month", summary: "Reduced-price plan for eligible students.", features: ["Student verification", "Individual access", "Regional availability"] },
    ]),
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    category: "Productivity",
    initials: "M",
    accent: "#2563EB",
    description: "A productivity subscription for office apps, cloud storage, and collaboration tools.",
    officialUrl: "https://www.microsoft.com/microsoft-365",
    managementUrl: "https://account.microsoft.com/services",
    managementHint: "Sign in to Microsoft services to review a directly billed personal subscription.",
    plans: plans([
      { id: "basic", name: "Personal", priceLabel: "US$9.99/month", summary: "Full apps and cloud storage for one person.", features: ["Desktop apps", "Cloud storage", "Personal use"] },
      { id: "personal", name: "Family", priceLabel: "US$12.99/month", summary: "Full apps and cloud storage for up to six people.", features: ["Multiple people", "Desktop apps", "Shared storage"] },
      { id: "family", name: "Premium", priceLabel: "US$19.99/month", summary: "Expanded AI and family plan capabilities.", features: ["Multiple people", "Desktop apps", "AI features"] },
    ]),
  },
  {
    id: "google-one",
    name: "Google One",
    category: "Cloud",
    initials: "G",
    accent: "#2563EB",
    description: "Cloud storage plans and member benefits linked to a Google account.",
    officialUrl: "https://one.google.com/",
    managementUrl: "https://one.google.com/settings",
    managementHint: "Open Google One settings to review storage and membership controls.",
    plans: plans([
      { id: "basic", name: "Basic storage", priceLabel: "US$1.99/month", summary: "Entry-level expanded storage.", features: ["Shared storage", "Google account", "Personal use"] },
      { id: "premium", name: "Standard storage", priceLabel: "US$2.99/month", summary: "More storage and selected benefits.", features: ["More storage", "Member benefits", "Family sharing"] },
      { id: "ai", name: "Google AI Pro", priceLabel: "US$19.99/month", summary: "Selected AI benefits in eligible regions.", features: ["AI features", "Storage", "Regional availability"] },
    ]),
  },
  {
    id: "notion",
    name: "Notion",
    category: "Productivity",
    initials: "No",
    accent: "#334155",
    description: "A connected workspace for notes, documents, projects, and knowledge sharing.",
    officialUrl: "https://www.notion.so/",
    managementUrl: "https://www.notion.so/",
    managementHint: "Open workspace settings to review subscription and billing options.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Core workspace for personal use.", features: ["Notes", "Pages", "Personal workspace"] },
      { id: "plus", name: "Plus", priceLabel: "US$10/member/month", summary: "Expanded collaboration capabilities.", features: ["More collaboration", "Sharing", "Expanded history"] },
      { id: "business", name: "Business", priceLabel: "US$20/member/month", summary: "Team-oriented controls and administration.", features: ["Admin controls", "Team workspace", "Advanced collaboration"] },
    ]),
  },
  {
    id: "apple-music",
    name: "Apple Music",
    category: "Music",
    initials: "AM",
    accent: "#DB2777",
    description: "Music streaming that may be billed directly by Apple or through a bundled provider.",
    officialUrl: "https://music.apple.com/",
    managementUrl: "https://account.apple.com/account/manage/section/subscriptions",
    managementHint: "Apple-billed plans are managed through Apple Account subscriptions.",
    plans: plans([
      { id: "student", name: "Student", priceLabel: "US$6.99/month", summary: "Individual music plan for eligible students.", features: ["Student eligibility", "Personal account", "Music library"] },
      { id: "individual", name: "Individual", priceLabel: "US$11.99/month", summary: "Personal streaming subscription.", features: ["Ad-free music", "Offline downloads", "Personal library"] },
      { id: "family", name: "Family", priceLabel: "US$19.99/month", summary: "Shared plan within an eligible family group.", features: ["Family group", "Multiple people", "Personal libraries"] },
    ]),
  },
  {
    id: "headspace",
    name: "Headspace",
    category: "Fitness",
    initials: "H",
    accent: "#EA580C",
    description: "A mindfulness and meditation membership with personal and shared options.",
    officialUrl: "https://www.headspace.com/",
    managementUrl: "https://www.headspace.com/",
    managementHint: "Sign in to review your account. Check Apple or Google if a store billed the subscription.",
    plans: plans([
      { id: "monthly", name: "Monthly", priceLabel: "Varies by country", summary: "Flexible membership cadence.", features: ["Guided sessions", "Sleep content", "Monthly billing"] },
      { id: "annual", name: "Annual", cadence: "yearly", priceLabel: "Varies by country", summary: "Annual membership cadence.", features: ["Guided sessions", "Sleep content", "Annual billing"] },
      { id: "family", name: "Family", priceLabel: "Varies by country", summary: "Shared wellness membership where available.", features: ["Multiple members", "Guided sessions", "Regional terms"] },
    ]),
  },
  {
    id: "coursera",
    name: "Coursera",
    category: "Learning",
    initials: "Co",
    accent: "#1D4ED8",
    description: "Online courses and learning memberships for professional and personal development.",
    officialUrl: "https://www.coursera.org/",
    managementUrl: "https://www.coursera.org/",
    managementHint: "Sign in and review account settings or the original billing channel.",
    plans: plans([
      { id: "course", name: "Single course", priceLabel: "Varies by offering", summary: "Course-specific access.", features: ["Selected course", "Course schedule", "Certificate options"] },
      { id: "plus-monthly", name: "Plus monthly", priceLabel: "US$59/month", summary: "Monthly learning membership.", features: ["Eligible catalog", "Monthly billing", "Learning paths"] },
      { id: "plus-annual", name: "Plus annual", cadence: "yearly", priceLabel: "US$399/year", summary: "Annual learning membership.", features: ["Eligible catalog", "Annual billing", "Learning paths"] },
    ]),
  },
  {
    id: "playstation-plus",
    name: "PlayStation Plus",
    category: "Gaming",
    initials: "PS",
    accent: "#1E40AF",
    description: "A console membership with online play and catalog benefits that differ by tier and region.",
    officialUrl: "https://www.playstation.com/ps-plus/",
    managementUrl: "https://www.playstation.com/",
    managementHint: "Sign in to PlayStation account management or check the store used for billing.",
    plans: plans([
      { id: "essential", name: "Essential", priceLabel: "Varies by country", summary: "Core membership tier.", features: ["Online multiplayer", "Monthly games", "Cloud saves"] },
      { id: "extra", name: "Extra", priceLabel: "Varies by country", summary: "Expanded catalog tier.", features: ["Game catalog", "Online multiplayer", "Cloud saves"] },
      { id: "premium", name: "Premium", priceLabel: "Varies by country", summary: "Highest membership tier.", features: ["Classics catalog", "Trials where available", "Cloud streaming where available"] },
    ]),
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: "AI & work",
    initials: "P",
    accent: "#2563EB",
    description: "An AI-powered answer engine with cited search, research, document, and workspace tools.",
    officialUrl: "https://www.perplexity.ai/",
    managementUrl: "https://www.perplexity.ai/",
    managementHint: "Sign in, then open your account and billing settings to review a direct plan.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Core answers and limited use.", features: ["Cited answers", "Limited use", "Basic models"] },
      { id: "pro", name: "Pro", priceLabel: "US$20/month", summary: "Expanded research and model access.", features: ["Deep research", "More usage", "Model selection"] },
      { id: "max", name: "Max", priceLabel: "US$200/month", summary: "Highest usage and capability limits.", features: ["Highest limits", "Advanced research", "Priority access"] },
    ]),
  },
  {
    id: "grammarly",
    name: "Grammarly",
    category: "AI & work",
    initials: "G",
    accent: "#0F766E",
    description: "Writing assistance and AI communication tools for drafting, rewrites, tone, and clarity.",
    officialUrl: "https://www.grammarly.com/",
    managementUrl: "https://account.grammarly.com/",
    managementHint: "Sign in to your Grammarly account to review the plan and billing options.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Core writing suggestions.", features: ["Grammar checks", "Basic rewrites", "Personal use"] },
      { id: "pro-monthly", name: "Pro monthly", priceLabel: "US$30/month", summary: "Flexible premium writing assistance.", features: ["More AI prompts", "Tone support", "Premium suggestions"] },
      { id: "pro-annual", name: "Pro annual", cadence: "yearly", priceLabel: "US$144/year", summary: "Annual Pro billing at an average of US$12/month.", features: ["Annual billing", "Premium suggestions", "More AI prompts"] },
    ]),
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "Cloud",
    initials: "D",
    accent: "#2563EB",
    description: "Cloud storage and file sharing for personal work, collaboration, and device access.",
    officialUrl: "https://www.dropbox.com/plans",
    managementUrl: "https://www.dropbox.com/account/plan",
    managementHint: "Sign in to your Dropbox account to view storage, billing, and cancellation options.",
    plans: plans([
      { id: "basic", name: "Basic", priceLabel: "No subscription", summary: "Included entry-level cloud storage.", features: ["Cloud storage", "File sharing", "Personal use"] },
      { id: "plus", name: "Plus", priceLabel: "US$9.99/month", summary: "Personal 2 TB storage plan.", features: ["2 TB storage", "File recovery", "Personal plan"] },
      { id: "professional", name: "Professional", priceLabel: "See official price", summary: "Expanded tools for individual professionals.", features: ["More storage", "Sharing tools", "Professional workflow"] },
    ]),
  },
  {
    id: "canva",
    name: "Canva",
    category: "Productivity",
    initials: "Ca",
    accent: "#0EA5A8",
    description: "A visual design workspace for presentations, social content, documents, and brand assets.",
    officialUrl: "https://www.canva.com/pricing/",
    managementUrl: "https://www.canva.com/settings/billing/",
    managementHint: "Sign in to Canva and open billing settings to review your plan or billing source.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Core design tools and templates.", features: ["Templates", "Design tools", "Personal projects"] },
      { id: "pro", name: "Pro", priceLabel: "See official price", summary: "Expanded design, brand, and content tools.", features: ["Brand tools", "Premium content", "More AI tools"] },
      { id: "business", name: "Business", priceLabel: "See official price", summary: "Team-oriented controls and shared workflows.", features: ["Team workspace", "Admin controls", "Shared content"] },
    ]),
  },
  {
    id: "disney-plus",
    name: "Disney+",
    category: "Entertainment",
    initials: "D+",
    accent: "#1D4ED8",
    description: "A streaming service for Disney, Pixar, Marvel, Star Wars, and National Geographic entertainment.",
    officialUrl: "https://www.disneyplus.com/",
    managementUrl: "https://www.disneyplus.com/",
    managementHint: "Sign in to Disney+ to view membership controls, or check your original billing provider.",
    plans: plans([
      { id: "standard-ads", name: "Standard with ads", priceLabel: "See official price", summary: "Ad-supported streaming in eligible markets.", features: ["Streaming access", "Ad-supported", "Regional availability"] },
      { id: "premium", name: "Premium", priceLabel: "See official price", summary: "Expanded viewing features where offered.", features: ["Ad-free options", "Higher quality", "Regional availability"] },
      { id: "bundle", name: "Bundle", priceLabel: "See official price", summary: "Disney+ may be available in eligible service bundles.", features: ["Bundle billing", "Multiple services", "Regional availability"] },
    ]),
  },
  {
    id: "hulu",
    name: "Hulu",
    category: "Entertainment",
    initials: "H",
    accent: "#15803D",
    description: "Streaming television and on-demand entertainment with standalone and bundle options.",
    officialUrl: "https://www.hulu.com/",
    managementUrl: "https://www.hulu.com/account",
    managementHint: "Sign in to Hulu to review your plan, add-ons, and billing method.",
    plans: plans([
      { id: "ads", name: "With ads", priceLabel: "See official price", summary: "Ad-supported on-demand streaming.", features: ["On-demand shows", "Ad-supported", "Monthly billing"] },
      { id: "no-ads", name: "No ads", priceLabel: "See official price", summary: "Reduced advertising where eligible.", features: ["On-demand shows", "Fewer ads", "Monthly billing"] },
      { id: "bundle", name: "Bundle", priceLabel: "See official price", summary: "Hulu may be bundled with other streaming services.", features: ["Bundle billing", "Multiple services", "Regional availability"] },
    ]),
  },
  {
    id: "audible",
    name: "Audible",
    category: "Music",
    initials: "Au",
    accent: "#EA580C",
    description: "Audiobook and spoken-word membership plans with monthly credits and included listening catalog access.",
    officialUrl: "https://www.audible.com/ep/memberbenefits",
    managementUrl: "https://www.audible.com/account/overview",
    managementHint: "Sign in through Audible or Amazon to review your membership and cancellation controls.",
    plans: plans([
      { id: "standard", name: "Standard", priceLabel: "US$8.99/month", summary: "Monthly membership after the trial period.", features: ["Monthly selection", "Audiobook access", "Cancel anytime"] },
      { id: "premium", name: "Premium", priceLabel: "US$14.95/month", summary: "Monthly credit membership with Plus Catalog access.", features: ["One credit monthly", "Plus Catalog", "Member discounts"] },
      { id: "premium-annual", name: "Premium annual", cadence: "yearly", priceLabel: "US$149.50/year", summary: "Annual 12-credit Premium membership.", features: ["12 annual credits", "Plus Catalog", "Annual billing"] },
    ]),
  },
  {
    id: "strava",
    name: "Strava",
    category: "Fitness",
    initials: "St",
    accent: "#F97316",
    description: "Activity tracking and fitness community membership for routes, training, and performance insights.",
    officialUrl: "https://www.strava.com/pricing",
    managementUrl: "https://www.strava.com/settings/billing",
    managementHint: "Sign in to Strava to review your subscription and current billing channel.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Core activity tracking and community features.", features: ["Activity tracking", "Community", "Basic analysis"] },
      { id: "subscription", name: "Subscription", priceLabel: "US$11.99/month", summary: "Expanded training, route, and progress features.", features: ["Training tools", "Routes", "Advanced analysis"] },
      { id: "annual", name: "Annual", cadence: "yearly", priceLabel: "US$79.99/year", summary: "Annual individual subscription.", features: ["Annual billing", "Training tools", "Route planning"] },
    ]),
  },
  {
    id: "xbox-game-pass",
    name: "Xbox Game Pass",
    category: "Gaming",
    initials: "X",
    accent: "#15803D",
    description: "A gaming membership with console, PC, cloud, multiplayer, and catalog features that vary by plan.",
    officialUrl: "https://www.xbox.com/xbox-game-pass",
    managementUrl: "https://account.microsoft.com/services",
    managementHint: "Sign in to Microsoft services to review Game Pass recurring billing and cancellation controls.",
    plans: plans([
      { id: "essential", name: "Essential", priceLabel: "See official price", summary: "Core game catalog, cloud, and multiplayer features.", features: ["Game catalog", "Cloud gaming", "Multiplayer"] },
      { id: "premium", name: "Premium", priceLabel: "See official price", summary: "Expanded catalog and cloud features.", features: ["Larger catalog", "Cloud gaming", "Rewards"] },
      { id: "ultimate", name: "Ultimate", priceLabel: "See official price", summary: "Highest-tier Game Pass benefits.", features: ["Day-one titles", "EA Play", "Cloud gaming"] },
    ]),
  },
  {
    id: "duolingo",
    name: "Duolingo",
    category: "Learning",
    initials: "Du",
    accent: "#65A30D",
    description: "Language learning with ad-free and AI-enhanced subscription options that vary by region and platform.",
    officialUrl: "https://www.duolingo.com/",
    managementUrl: "https://www.duolingo.com/",
    managementHint: "Sign in to Duolingo and check the app store or web billing source used for your subscription.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Core language-learning lessons with ads and limits.", features: ["Lessons", "Practice", "Ad-supported"] },
      { id: "super", name: "Super Duolingo", priceLabel: "See official price", summary: "Ad-free learning with expanded practice tools.", features: ["Ad-free learning", "Practice tools", "Offline access"] },
      { id: "max", name: "Duolingo Max", priceLabel: "See official price", summary: "AI-enhanced learning features in eligible plans and markets.", features: ["AI features", "Personalized practice", "Regional availability"] },
    ]),
  },
];

export const categoryOrder = ["All", "AI & work", "Entertainment", "Music", "Productivity", "Cloud", "Fitness", "Learning", "Gaming"] as const;

export const billingSourceMeta: Record<BillingSource, { label: string; description: string; url?: string }> = {
  apple: {
    label: "Apple App Store",
    description: "Apple controls renewal and cancellation for this store-billed subscription.",
    url: "https://apps.apple.com/account/subscriptions",
  },
  google: {
    label: "Google Play",
    description: "Google controls renewal and cancellation for this store-billed subscription.",
    url: "https://play.google.com/store/account/subscriptions",
  },
  provider: {
    label: "Provider website",
    description: "The service provider controls this direct subscription.",
  },
  carrier: {
    label: "Mobile carrier or bundle",
    description: "Your carrier or bundle provider may control renewal and cancellation.",
  },
  reseller: {
    label: "Reseller or marketplace",
    description: "The reseller or marketplace that billed you may control this subscription.",
  },
  unknown: {
    label: "Unknown billing source",
    description: "Check your receipt, bank statement, or account email before attempting to cancel.",
  },
};

export function getService(serviceId: string | undefined) {
  return services.find((service) => service.id === serviceId);
}
