import type { BillingSource, CatalogPlan, ServiceDefinition } from "./subscription-types";

const plans = (items: Array<Omit<CatalogPlan, "cadence"> & { cadence?: CatalogPlan["cadence"] }>) =>
  items.map((item) => ({ cadence: "monthly" as const, ...item }));

export const serviceLogoSources: Record<string, string> = {
  chatgpt: "https://commons.wikimedia.org/wiki/Special:FilePath/ChatGPT_logo.svg",
  claude: "https://cdn.simpleicons.org/anthropic",
  netflix: "https://cdn.simpleicons.org/netflix",
  "prime-video": "https://commons.wikimedia.org/wiki/Special:FilePath/Amazon_Prime_logo.svg",
  spotify: "https://cdn.simpleicons.org/spotify",
  "youtube-premium": "https://cdn.simpleicons.org/youtube",
  "microsoft-365": "https://cdn.simpleicons.org/microsoft",
  "google-one": "https://cdn.simpleicons.org/google",
  notion: "https://cdn.simpleicons.org/notion",
  "apple-music": "https://cdn.simpleicons.org/applemusic",
  headspace: "https://cdn.simpleicons.org/headspace",
  coursera: "https://cdn.simpleicons.org/coursera",
  "playstation-plus": "https://cdn.simpleicons.org/playstation",
};

export const services: ServiceDefinition[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: "AI & work",
    initials: "C",
    accent: "#0F766E",
    description: "A conversational AI workspace for writing, analysis, research, and everyday tasks.",
    officialUrl: "https://chatgpt.com/",
    managementUrl: "https://chatgpt.com/",
    managementHint: "Sign in, then open Settings to review your plan and billing options.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Core everyday AI access.", features: ["General chat", "Basic access", "Personal use"] },
      { id: "plus", name: "Plus", priceLabel: "See official pricing", summary: "Expanded access for frequent individual use.", features: ["Higher limits", "Priority access", "More tools"] },
      { id: "pro", name: "Pro", priceLabel: "See official pricing", summary: "Higher-capacity access for power users.", features: ["Highest limits", "Advanced tools", "Priority access"] },
    ]),
  },
  {
    id: "claude",
    name: "Claude",
    category: "AI & work",
    initials: "Cl",
    accent: "#C76B42",
    description: "An AI assistant for writing, reasoning, document work, and creative tasks.",
    officialUrl: "https://claude.ai/",
    managementUrl: "https://claude.ai/",
    managementHint: "Sign in, then open account settings to view plan and billing controls.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Try core AI capabilities.", features: ["Core chat", "Limited use", "Personal workspace"] },
      { id: "pro", name: "Pro", priceLabel: "See official pricing", summary: "More capacity for regular work.", features: ["Higher usage", "Priority access", "More features"] },
      { id: "max", name: "Max", priceLabel: "See official pricing", summary: "Expanded access for intensive usage.", features: ["High capacity", "Priority access", "Advanced usage"] },
    ]),
  },
  {
    id: "netflix",
    name: "Netflix",
    category: "Entertainment",
    initials: "N",
    accent: "#B91C1C",
    description: "A streaming entertainment service with plans that vary by country and feature set.",
    officialUrl: "https://www.netflix.com/",
    managementUrl: "https://www.netflix.com/cancelplan",
    managementHint: "Sign in to review membership or cancellation options for direct Netflix billing.",
    plans: plans([
      { id: "standard-ads", name: "Standard with ads", priceLabel: "Varies by country", summary: "Streaming access with advertising in eligible regions.", features: ["Ad-supported", "Selected devices", "Regional availability"] },
      { id: "standard", name: "Standard", priceLabel: "Varies by country", summary: "Ad-free streaming for most households.", features: ["Ad-free viewing", "Multiple devices", "HD where available"] },
      { id: "premium", name: "Premium", priceLabel: "Varies by country", summary: "Highest available quality and device allowance.", features: ["More devices", "Higher quality", "Ad-free viewing"] },
    ]),
  },
  {
    id: "prime-video",
    name: "Amazon Prime",
    category: "Entertainment",
    initials: "A",
    accent: "#1D4ED8",
    description: "A membership that can include delivery, entertainment, and regional benefits.",
    officialUrl: "https://www.amazon.com/prime",
    managementUrl: "https://www.amazon.com/gp/primecentral",
    managementHint: "Sign in to Amazon and open Prime Membership to review your direct membership.",
    plans: plans([
      { id: "monthly", name: "Monthly", priceLabel: "Varies by country", summary: "Flexible membership cadence.", features: ["Monthly billing", "Prime benefits", "Regional terms"] },
      { id: "annual", name: "Annual", cadence: "yearly", priceLabel: "Varies by country", summary: "Annual membership cadence.", features: ["Annual billing", "Prime benefits", "Regional terms"] },
      { id: "video", name: "Prime Video", priceLabel: "Varies by country", summary: "Video access may be offered separately in some regions.", features: ["Video access", "Regional catalog", "Optional channels"] },
    ]),
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "Music",
    initials: "S",
    accent: "#15803D",
    description: "Music and audio streaming with individual, shared, and student options in supported regions.",
    officialUrl: "https://www.spotify.com/",
    managementUrl: "https://www.spotify.com/account/subscription/",
    managementHint: "Sign in to review your plan. If billed by a partner, Spotify will identify that provider.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Ad-supported listening.", features: ["Ad-supported", "Core music access", "Mobile limits"] },
      { id: "premium", name: "Premium Individual", priceLabel: "Varies by country", summary: "Ad-free listening for one account.", features: ["Ad-free", "Offline listening", "Individual account"] },
      { id: "family", name: "Premium Family", priceLabel: "Varies by country", summary: "A household plan where available.", features: ["Multiple accounts", "Household plan", "Parental features"] },
    ]),
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    category: "Entertainment",
    initials: "Y",
    accent: "#DC2626",
    description: "An ad-free YouTube membership with region-dependent plan and family options.",
    officialUrl: "https://www.youtube.com/premium",
    managementUrl: "https://www.youtube.com/paid_memberships",
    managementHint: "Open paid memberships while signed in to review eligible plan controls.",
    plans: plans([
      { id: "individual", name: "Individual", priceLabel: "Varies by country", summary: "Ad-free viewing for one person.", features: ["Ad-free viewing", "Background play", "Downloads"] },
      { id: "family", name: "Family", priceLabel: "Varies by country", summary: "Shared household access where available.", features: ["Multiple members", "Household rules", "Regional availability"] },
      { id: "student", name: "Student", priceLabel: "Eligibility required", summary: "Reduced-price plan for eligible students.", features: ["Student verification", "Individual access", "Regional availability"] },
    ]),
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    category: "Productivity",
    initials: "M",
    accent: "#2563EB",
    description: "A productivity subscription for office apps, cloud storage, and collaboration tools.",
    officialUrl: "https://www.microsoft.com/microsoft-365",
    managementUrl: "https://account.microsoft.com/services",
    managementHint: "Sign in to Microsoft services to review a directly billed personal subscription.",
    plans: plans([
      { id: "basic", name: "Basic", priceLabel: "Varies by country", summary: "Essential storage and productivity access.", features: ["Cloud storage", "Web apps", "Personal use"] },
      { id: "personal", name: "Personal", priceLabel: "Varies by country", summary: "Full apps for one person.", features: ["Desktop apps", "Cloud storage", "Personal use"] },
      { id: "family", name: "Family", priceLabel: "Varies by country", summary: "Shared access for a household.", features: ["Multiple people", "Desktop apps", "Shared storage"] },
    ]),
  },
  {
    id: "google-one",
    name: "Google One",
    category: "Cloud",
    initials: "G",
    accent: "#2563EB",
    description: "Cloud storage plans and member benefits linked to a Google account.",
    officialUrl: "https://one.google.com/",
    managementUrl: "https://one.google.com/settings",
    managementHint: "Open Google One settings to review storage and membership controls.",
    plans: plans([
      { id: "basic", name: "Basic storage", priceLabel: "Varies by country", summary: "Entry-level expanded storage.", features: ["Shared storage", "Google account", "Personal use"] },
      { id: "premium", name: "Premium storage", priceLabel: "Varies by country", summary: "More storage and selected benefits.", features: ["More storage", "Member benefits", "Family sharing"] },
      { id: "ai", name: "AI plan", priceLabel: "Varies by country", summary: "Selected AI benefits in eligible regions.", features: ["AI features", "Storage", "Regional availability"] },
    ]),
  },
  {
    id: "notion",
    name: "Notion",
    category: "Productivity",
    initials: "No",
    accent: "#334155",
    description: "A connected workspace for notes, documents, projects, and knowledge sharing.",
    officialUrl: "https://www.notion.so/",
    managementUrl: "https://www.notion.so/",
    managementHint: "Open workspace settings to review subscription and billing options.",
    plans: plans([
      { id: "free", name: "Free", priceLabel: "No subscription", summary: "Core workspace for personal use.", features: ["Notes", "Pages", "Personal workspace"] },
      { id: "plus", name: "Plus", priceLabel: "See official pricing", summary: "Expanded collaboration capabilities.", features: ["More collaboration", "Sharing", "Expanded history"] },
      { id: "business", name: "Business", priceLabel: "See official pricing", summary: "Team-oriented controls and administration.", features: ["Admin controls", "Team workspace", "Advanced collaboration"] },
    ]),
  },
  {
    id: "apple-music",
    name: "Apple Music",
    category: "Music",
    initials: "AM",
    accent: "#DB2777",
    description: "Music streaming that may be billed directly by Apple or through a bundled provider.",
    officialUrl: "https://music.apple.com/",
    managementUrl: "https://account.apple.com/account/manage/section/subscriptions",
    managementHint: "Apple-billed plans are managed through Apple Account subscriptions.",
    plans: plans([
      { id: "student", name: "Student", priceLabel: "Eligibility required", summary: "Individual music plan for eligible students.", features: ["Student eligibility", "Personal account", "Music library"] },
      { id: "individual", name: "Individual", priceLabel: "Varies by country", summary: "Personal streaming subscription.", features: ["Ad-free music", "Offline downloads", "Personal library"] },
      { id: "family", name: "Family", priceLabel: "Varies by country", summary: "Shared plan within an eligible family group.", features: ["Family group", "Multiple people", "Personal libraries"] },
    ]),
  },
  {
    id: "headspace",
    name: "Headspace",
    category: "Fitness",
    initials: "H",
    accent: "#EA580C",
    description: "A mindfulness and meditation membership with personal and shared options.",
    officialUrl: "https://www.headspace.com/",
    managementUrl: "https://www.headspace.com/",
    managementHint: "Sign in to review your account. Check Apple or Google if a store billed the subscription.",
    plans: plans([
      { id: "monthly", name: "Monthly", priceLabel: "Varies by country", summary: "Flexible membership cadence.", features: ["Guided sessions", "Sleep content", "Monthly billing"] },
      { id: "annual", name: "Annual", cadence: "yearly", priceLabel: "Varies by country", summary: "Annual membership cadence.", features: ["Guided sessions", "Sleep content", "Annual billing"] },
      { id: "family", name: "Family", priceLabel: "Varies by country", summary: "Shared wellness membership where available.", features: ["Multiple members", "Guided sessions", "Regional terms"] },
    ]),
  },
  {
    id: "coursera",
    name: "Coursera",
    category: "Learning",
    initials: "Co",
    accent: "#1D4ED8",
    description: "Online courses and learning memberships for professional and personal development.",
    officialUrl: "https://www.coursera.org/",
    managementUrl: "https://www.coursera.org/",
    managementHint: "Sign in and review account settings or the original billing channel.",
    plans: plans([
      { id: "course", name: "Single course", priceLabel: "Varies by offering", summary: "Course-specific access.", features: ["Selected course", "Course schedule", "Certificate options"] },
      { id: "plus-monthly", name: "Plus monthly", priceLabel: "Varies by country", summary: "Monthly learning membership.", features: ["Eligible catalog", "Monthly billing", "Learning paths"] },
      { id: "plus-annual", name: "Plus annual", cadence: "yearly", priceLabel: "Varies by country", summary: "Annual learning membership.", features: ["Eligible catalog", "Annual billing", "Learning paths"] },
    ]),
  },
  {
    id: "playstation-plus",
    name: "PlayStation Plus",
    category: "Gaming",
    initials: "PS",
    accent: "#1E40AF",
    description: "A console membership with online play and catalog benefits that differ by tier and region.",
    officialUrl: "https://www.playstation.com/ps-plus/",
    managementUrl: "https://www.playstation.com/",
    managementHint: "Sign in to PlayStation account management or check the store used for billing.",
    plans: plans([
      { id: "essential", name: "Essential", priceLabel: "Varies by country", summary: "Core membership tier.", features: ["Online multiplayer", "Monthly games", "Cloud saves"] },
      { id: "extra", name: "Extra", priceLabel: "Varies by country", summary: "Expanded catalog tier.", features: ["Game catalog", "Online multiplayer", "Cloud saves"] },
      { id: "premium", name: "Premium", priceLabel: "Varies by country", summary: "Highest membership tier.", features: ["Classics catalog", "Trials where available", "Cloud streaming where available"] },
    ]),
  },
];

export const categoryOrder = ["All", "AI & work", "Entertainment", "Music", "Productivity", "Cloud", "Fitness", "Learning", "Gaming"] as const;

export const billingSourceMeta: Record<BillingSource, { label: string; description: string; url?: string }> = {
  apple: {
    label: "Apple App Store",
    description: "Apple controls renewal and cancellation for this store-billed subscription.",
    url: "https://apps.apple.com/account/subscriptions",
  },
  google: {
    label: "Google Play",
    description: "Google controls renewal and cancellation for this store-billed subscription.",
    url: "https://play.google.com/store/account/subscriptions",
  },
  provider: {
    label: "Provider website",
    description: "The service provider controls this direct subscription.",
  },
  carrier: {
    label: "Mobile carrier or bundle",
    description: "Your carrier or bundle provider may control renewal and cancellation.",
  },
  reseller: {
    label: "Reseller or marketplace",
    description: "The reseller or marketplace that billed you may control this subscription.",
  },
  unknown: {
    label: "Unknown billing source",
    description: "Check your receipt, bank statement, or account email before attempting to cancel.",
  },
};

export function getService(serviceId: string | undefined) {
  return services.find((service) => service.id === serviceId);
}
