import { router } from "expo-router";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { EmptyState, Pill, PrimaryButton, SectionLabel, ServiceBadge, SubscriptionRow } from "@/components/subscription-ui";
import { RenewalCalendar } from "@/components/renewal-calendar";
import { getService } from "@/lib/catalog";
import { useSubscriptions } from "@/lib/subscription-store";
import { formatCurrency, getUpcomingSubscriptions, totalAnnual, totalMonthly } from "@/lib/subscription-utils";
import { ScreenContainer } from "@/components/screen-container";

const type = { regular: "Poppins-Regular", semi: "Poppins-SemiBold", bold: "Poppins-Bold" };

export default function HomeScreen() {
  const { isReady, subscriptions } = useSubscriptions();
  const upcoming = getUpcomingSubscriptions(subscriptions).slice(0, 3);
  const activeCount = subscriptions.filter((item) => item.status !== "cancelled").length;
  if (!isReady) return <ScreenContainer><View style={styles.loading}><ActivityIndicator color="#1A73E8" /></View></ScreenContainer>;
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.brand}>SubTrack</Text><Text style={styles.headerCaption}>Your subscription overview</Text></View><Pressable onPress={() => router.push("/(tabs)/discover")} style={({ pressed }) => [styles.addButton, pressed && styles.pressed]}><Text style={styles.addText}>+</Text></Pressable></View>
    <View style={styles.summaryCard}><View style={styles.summaryTop}><Text style={styles.summaryLabel}>MONTHLY SPEND</Text><Pill label={`${activeCount} active`} tone="teal" /></View><Text style={styles.summaryAmount}>{formatCurrency(totalMonthly(subscriptions))}</Text><View style={styles.summaryDivider} /><View style={styles.summaryFooter}><Text style={styles.summaryFooterLabel}>Annual estimate</Text><Text style={styles.summaryFooterValue}>{formatCurrency(totalAnnual(subscriptions))}</Text></View></View>
    <View style={styles.infoRow}><View style={styles.infoIcon}><Text style={styles.infoIconText}>✓</Text></View><View style={{ flex: 1 }}><Text style={styles.infoTitle}>Private by design</Text><Text style={styles.infoBody}>Your subscription list stays on this device. No bank or inbox access.</Text></View></View>
    <View style={styles.section}><SectionLabel title="Upcoming" action={subscriptions.length ? "See all" : undefined} onAction={() => router.push("/(tabs)/subscriptions")} />{upcoming.length ? <View style={styles.list}>{upcoming.map((item) => <SubscriptionRow key={item.id} item={item} onPress={() => router.push(`/subscription/${item.id}` as never)} />)}</View> : <EmptyState title="Start your subscription list" body="Add a service to see renewal dates, trial reminders, and a clear monthly total." />}</View>
    <View style={styles.section}><RenewalCalendar subscriptions={subscriptions} /></View>
    <View style={styles.section}><SectionLabel title="Popular services" action="Browse all" onAction={() => router.push("/(tabs)/discover")} /><View style={styles.services}>{["chatgpt", "netflix", "spotify", "google-one"].map((serviceId) => { const service = getService(serviceId)!; return <Pressable key={serviceId} onPress={() => router.push(`/service/${serviceId}`)} style={({ pressed }) => [styles.service, pressed && styles.pressed]}><ServiceBadge serviceId={serviceId} size="small" /><Text numberOfLines={1} style={styles.serviceName}>{service.name}</Text><Text style={styles.serviceCategory}>{service.category}</Text></Pressable>; })}</View></View>
    {!subscriptions.length ? <PrimaryButton label="Add a subscription" onPress={() => router.push("/(tabs)/discover")} /> : null}
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ loading: { alignItems: "center", flex: 1, justifyContent: "center" }, content: { gap: 24, paddingBottom: 28, paddingTop: 14 }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, brand: { color: "#202124", fontFamily: type.bold, fontSize: 25, letterSpacing: -0.8 }, headerCaption: { color: "#5F6368", fontFamily: type.regular, fontSize: 12, marginTop: 2 }, addButton: { alignItems: "center", backgroundColor: "#E8F0FE", borderRadius: 22, height: 44, justifyContent: "center", width: 44 }, addText: { color: "#1A73E8", fontFamily: type.regular, fontSize: 28, lineHeight: 29 }, summaryCard: { backgroundColor: "#FFFFFF", borderColor: "#DADCE0", borderRadius: 16, borderWidth: 1, padding: 20 }, summaryTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, summaryLabel: { color: "#5F6368", fontFamily: type.semi, fontSize: 10, letterSpacing: 1 }, summaryAmount: { color: "#202124", fontFamily: type.bold, fontSize: 36, letterSpacing: -1.3, marginTop: 8 }, summaryDivider: { backgroundColor: "#E8EAED", height: 1, marginTop: 19 }, summaryFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 12 }, summaryFooterLabel: { color: "#5F6368", fontFamily: type.regular, fontSize: 12 }, summaryFooterValue: { color: "#202124", fontFamily: type.semi, fontSize: 12 }, infoRow: { alignItems: "flex-start", backgroundColor: "#F8F9FA", borderColor: "#E8EAED", borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 10, padding: 13 }, infoIcon: { alignItems: "center", backgroundColor: "#E6F4EA", borderRadius: 12, height: 24, justifyContent: "center", width: 24 }, infoIconText: { color: "#188038", fontFamily: type.bold, fontSize: 12 }, infoTitle: { color: "#3C4043", fontFamily: type.semi, fontSize: 12 }, infoBody: { color: "#5F6368", fontFamily: type.regular, fontSize: 11, lineHeight: 16, marginTop: 2 }, section: {}, list: { gap: 10 }, services: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, service: { backgroundColor: "#FFFFFF", borderColor: "#DADCE0", borderRadius: 14, borderWidth: 1, padding: 12, width: "48.5%" }, serviceName: { color: "#202124", fontFamily: type.semi, fontSize: 12, marginTop: 8 }, serviceCategory: { color: "#5F6368", fontFamily: type.regular, fontSize: 10, marginTop: 2 }, pressed: { opacity: 0.74, transform: [{ scale: 0.99 }] } });
