import { router } from "expo-router";
import { Alert, Pressable, ScrollView, Share, StyleSheet, Switch, Text, View } from "react-native";

import { useSubscriptions } from "@/lib/subscription-store";
import { ScreenContainer } from "@/components/screen-container";

const type = { regular: "Poppins-Regular", semi: "Poppins-SemiBold", bold: "Poppins-Bold" };

export default function SettingsScreen() {
  const { settings, subscriptions, updateSettings, resetLocalData } = useSubscriptions();
  const exportData = async () => { await Share.share({ title: "My SubTrack data", message: JSON.stringify({ subscriptions, settings, exportedAt: new Date().toISOString() }, null, 2) }); };
  const reset = () => Alert.alert("Reset local data?", "This removes all local subscription records and reminders. It does not cancel any provider subscription.", [{ text: "Cancel", style: "cancel" }, { text: "Reset", style: "destructive", onPress: () => void resetLocalData() }]);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.title}>Settings</Text><Text style={styles.subtitle}>Privacy and reminder preferences.</Text>
    <View style={styles.privacy}><View style={styles.privacyMark}><Text style={styles.privacyMarkText}>✓</Text></View><View style={{ flex: 1 }}><Text style={styles.privacyTitle}>Stored on this device</Text><Text style={styles.privacyBody}>SubTrack does not request your bank details, email account, or service passwords.</Text></View></View>
    <Text style={styles.section}>Reminders</Text><View style={styles.group}><View style={styles.row}><View style={styles.rowCopy}><Text style={styles.rowTitle}>Renewal reminders</Text><Text style={styles.rowBody}>Receive local alerts before renewal dates.</Text></View><Switch value={settings.notificationsEnabled} onValueChange={(value) => void updateSettings({ notificationsEnabled: value })} trackColor={{ false: "#DADCE0", true: "#AECBFA" }} thumbColor={settings.notificationsEnabled ? "#1A73E8" : "#FFFFFF"} /></View><View style={styles.divider} /><View style={styles.row}><View style={styles.rowCopy}><Text style={styles.rowTitle}>Reminder lead time</Text><Text style={styles.rowBody}>Remind {settings.reminderDays} days before renewal.</Text></View><View style={styles.stepper}>{[1, 3, 7].map((days) => <Pressable key={days} onPress={() => void updateSettings({ reminderDays: days })} style={({ pressed }) => [styles.step, days === settings.reminderDays && styles.stepSelected, pressed && styles.pressed]}><Text style={[styles.stepText, days === settings.reminderDays && styles.stepTextSelected]}>{days}d</Text></Pressable>)}</View></View></View>
    <Text style={styles.section}>Your data</Text><View style={styles.group}><Pressable onPress={exportData} style={({ pressed }) => [styles.actionRow, pressed && styles.pressed]}><View><Text style={styles.rowTitle}>Export local data</Text><Text style={styles.rowBody}>Share a JSON backup of your saved records.</Text></View><Text style={styles.chevron}>›</Text></Pressable><View style={styles.divider} /><Pressable onPress={() => Alert.alert("Catalog feedback", "Please email feedback@subtrack.local with the service, country, plan, or link that needs correction.")} style={({ pressed }) => [styles.actionRow, pressed && styles.pressed]}><View><Text style={styles.rowTitle}>Report catalog information</Text><Text style={styles.rowBody}>Flag a plan, price, or official link.</Text></View><Text style={styles.chevron}>›</Text></Pressable><View style={styles.divider} /><Pressable onPress={reset} style={({ pressed }) => [styles.actionRow, pressed && styles.pressed]}><View><Text style={styles.deleteTitle}>Reset local data</Text><Text style={styles.rowBody}>Remove records stored on this device.</Text></View><Text style={styles.deleteChevron}>›</Text></Pressable></View>
    <View style={styles.footer}><Text style={styles.footerText}>SubTrack guides you to official management pages. It does not change or cancel a provider account.</Text><Pressable onPress={() => router.push("/(tabs)/discover")}><Text style={styles.footerLink}>Browse services</Text></Pressable></View>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 32, paddingTop: 16 }, title: { color: "#202124", fontFamily: type.bold, fontSize: 27, letterSpacing: -0.8 }, subtitle: { color: "#5F6368", fontFamily: type.regular, fontSize: 12, marginTop: 4 }, privacy: { alignItems: "flex-start", backgroundColor: "#E8F0FE", borderRadius: 16, flexDirection: "row", gap: 11, marginTop: 20, padding: 15 }, privacyMark: { alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 12, height: 24, justifyContent: "center", width: 24 }, privacyMarkText: { color: "#1A73E8", fontFamily: type.bold, fontSize: 12 }, privacyTitle: { color: "#174EA6", fontFamily: type.semi, fontSize: 13 }, privacyBody: { color: "#3C4043", fontFamily: type.regular, fontSize: 11, lineHeight: 16, marginTop: 3 }, section: { color: "#202124", fontFamily: type.semi, fontSize: 16, marginBottom: 9, marginTop: 24 }, group: { backgroundColor: "#FFFFFF", borderColor: "#DADCE0", borderRadius: 16, borderWidth: 1, overflow: "hidden" }, row: { alignItems: "center", flexDirection: "row", gap: 10, minHeight: 74, padding: 15 }, rowCopy: { flex: 1 }, rowTitle: { color: "#202124", fontFamily: type.semi, fontSize: 13 }, rowBody: { color: "#5F6368", fontFamily: type.regular, fontSize: 11, lineHeight: 16, marginTop: 3 }, divider: { backgroundColor: "#E8EAED", height: 1, marginLeft: 15 }, stepper: { backgroundColor: "#F1F3F4", borderRadius: 10, flexDirection: "row", padding: 3 }, step: { borderRadius: 8, paddingHorizontal: 7, paddingVertical: 6 }, stepSelected: { backgroundColor: "#FFFFFF" }, stepText: { color: "#5F6368", fontFamily: type.semi, fontSize: 10 }, stepTextSelected: { color: "#1A73E8" }, actionRow: { alignItems: "center", flexDirection: "row", gap: 10, justifyContent: "space-between", minHeight: 75, padding: 15 }, chevron: { color: "#9AA0A6", fontFamily: type.regular, fontSize: 25 }, deleteTitle: { color: "#C5221F", fontFamily: type.semi, fontSize: 13 }, deleteChevron: { color: "#D93025", fontFamily: type.regular, fontSize: 25 }, footer: { alignItems: "center", paddingHorizontal: 20, paddingTop: 24 }, footerText: { color: "#80868B", fontFamily: type.regular, fontSize: 10, lineHeight: 15, textAlign: "center" }, footerLink: { color: "#1A73E8", fontFamily: type.semi, fontSize: 12, marginTop: 11 }, pressed: { opacity: 0.75 } });
